//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace users.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal
    {
        public deal()
        {
            this.usercarts = new HashSet<usercart>();
            this.userhistories = new HashSet<userhistory>();
            this.userratings = new HashSet<userrating>();
            this.userreviews = new HashSet<userreview>();
        }
    
        public int dealId { get; set; }
        public int vendorId { get; set; }
        public int locationId { get; set; }
        public int bannerId { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string description { get; set; }
        public System.DateTime startsOn { get; set; }
        public System.DateTime endsOn { get; set; }
        public int count { get; set; }
        public string image { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> sold { get; set; }
        public float unitPrice { get; set; }
        public float discount { get; set; }
        public float sellingPrice { get; set; }
        public Nullable<bool> hasShipping { get; set; }
    
        public virtual banner banner { get; set; }
        public virtual category category { get; set; }
        public virtual location location { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual ICollection<usercart> usercarts { get; set; }
        public virtual ICollection<userhistory> userhistories { get; set; }
        public virtual ICollection<userrating> userratings { get; set; }
        public virtual ICollection<userreview> userreviews { get; set; }
    }
}
