//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace users.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderitems = new HashSet<orderitem>();
        }
    
        public int id { get; set; }
        public string orderId { get; set; }
        public Nullable<int> userId { get; set; }
        public int orderStatus { get; set; }
        public float subTotal { get; set; }
        public string promoCode { get; set; }
        public Nullable<float> promoDiscount { get; set; }
        public float grandTotal { get; set; }
        public int shippingId { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<orderitem> orderitems { get; set; }
        public virtual shippingaddress shippingaddress { get; set; }
        public virtual user user { get; set; }
    }
}
