//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace users.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userrating
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int dealId { get; set; }
        public int rating { get; set; }
        public System.DateTime dateCreated { get; set; }
        public bool isActive { get; set; }
    
        public virtual deal deal { get; set; }
        public virtual user user { get; set; }
    }
}
