//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string name { get; set; }
        public int pincode { get; set; }
        public string address1 { get; set; }
        public string landmark { get; set; }
        public string city { get; set; }
        public int state { get; set; }
        public string phone { get; set; }
        public bool isDefault { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool isActive { get; set; }
    
        public virtual state state1 { get; set; }
        public virtual user user { get; set; }
    }
}
