//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryconfig
    {
        public int id { get; set; }
        public int categoryId { get; set; }
        public int sequence { get; set; }
        public System.DateTime dateCreated { get; set; }
        public bool isActive { get; set; }
        public int displayItems { get; set; }
        public bool isMore { get; set; }
    
        public virtual category category { get; set; }
    }
}
