//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.categoryconfigs = new HashSet<categoryconfig>();
            this.deals = new HashSet<deal>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<categoryconfig> categoryconfigs { get; set; }
        public virtual ICollection<deal> deals { get; set; }
    }
}
