//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public int id { get; set; }
        public int orderId { get; set; }
        public int dealId { get; set; }
        public int quantity { get; set; }
        public float unitPrice { get; set; }
        public float discount { get; set; }
        public float sellingPrice { get; set; }
        public float subTotal { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool isActive { get; set; }
    
        public virtual order order { get; set; }
    }
}
