//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocode
    {
        public int promoId { get; set; }
        public string promoCode1 { get; set; }
        public int promoValue { get; set; }
        public int categoryId { get; set; }
        public System.DateTime createdOn { get; set; }
        public System.DateTime expiresOn { get; set; }
        public bool isPercentage { get; set; }
        public bool isActive { get; set; }
    }
}
