//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shippingaddress
    {
        public shippingaddress()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public string name { get; set; }
        public int pincode { get; set; }
        public string address { get; set; }
        public string landmark { get; set; }
        public string city { get; set; }
        public int state { get; set; }
        public string phone { get; set; }
        public System.DateTime createdOn { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
        public virtual user user { get; set; }
    }
}
