//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.addresses = new HashSet<address>();
            this.orders = new HashSet<order>();
            this.shippingaddresses = new HashSet<shippingaddress>();
            this.userhistories = new HashSet<userhistory>();
            this.userratings = new HashSet<userrating>();
            this.userreviews = new HashSet<userreview>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<shippingaddress> shippingaddresses { get; set; }
        public virtual ICollection<userhistory> userhistories { get; set; }
        public virtual ICollection<userrating> userratings { get; set; }
        public virtual ICollection<userreview> userreviews { get; set; }
    }
}
