//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.deals = new HashSet<deal>();
            this.usercarts = new HashSet<usercart>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string vendorname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime createddate { get; set; }
        public bool isactive { get; set; }
    
        public virtual ICollection<deal> deals { get; set; }
        public virtual ICollection<usercart> usercarts { get; set; }
    }
}
